export enum TTypeName {
  Any = "TAny",
  BigInt = "TBigInt",
  Boolean = "TBoolean",
  Defined = "TDefined",
  Intersection = "TIntersection",
  NaN = "TNaN",
  Never = "TNever",
  NonNullable = "TNonNullable",
  Not = "TNot",
  Null = "TNull",
  Nullable = "TNullable",
  Number = "TNumber",
  Optional = "TOptional",
  Promise = "TPromise",
  String = "TString",
  Symbol = "TSymbol",
  Undefined = "TUndefined",
  Union = "TUnion",
  Unknown = "TUnknown",
  Void = "TVoid",
}
