export enum TTypeName {
  Any = "TAny",
  Unknown = "TUnknown",
  Never = "TNever",
  String = "TString",
  Number = "TNumber",
  Boolean = "TBoolean",
  Null = "TNull",
  Undefined = "TUndefined",
  Void = "TVoid",
  Symbol = "TSymbol",
  Optional = "TOptional",
  Nullable = "TNullable",
  Defined = "TDefined",
}
